//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingPalsClientSide.parkingDB {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="parkingDB.ParkingDBWSSoap")]
    public interface ParkingDBWSSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ParkingPalsClientSide.parkingDB.HelloWorldResponse HelloWorld(ParkingPalsClientSide.parkingDB.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ParkingPalsClientSide.parkingDB.HelloWorldResponse> HelloWorldAsync(ParkingPalsClientSide.parkingDB.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 username 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PostUser", ReplyAction="*")]
        ParkingPalsClientSide.parkingDB.PostUserResponse PostUser(ParkingPalsClientSide.parkingDB.PostUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PostUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ParkingPalsClientSide.parkingDB.PostUserResponse> PostUserAsync(ParkingPalsClientSide.parkingDB.PostUserRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 username 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PutUser", ReplyAction="*")]
        ParkingPalsClientSide.parkingDB.PutUserResponse PutUser(ParkingPalsClientSide.parkingDB.PutUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PutUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ParkingPalsClientSide.parkingDB.PutUserResponse> PutUserAsync(ParkingPalsClientSide.parkingDB.PutUserRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 username 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsername", ReplyAction="*")]
        ParkingPalsClientSide.parkingDB.GetUsernameResponse GetUsername(ParkingPalsClientSide.parkingDB.GetUsernameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsername", ReplyAction="*")]
        System.Threading.Tasks.Task<ParkingPalsClientSide.parkingDB.GetUsernameResponse> GetUsernameAsync(ParkingPalsClientSide.parkingDB.GetUsernameRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 username 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmail", ReplyAction="*")]
        ParkingPalsClientSide.parkingDB.GetEmailResponse GetEmail(ParkingPalsClientSide.parkingDB.GetEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<ParkingPalsClientSide.parkingDB.GetEmailResponse> GetEmailAsync(ParkingPalsClientSide.parkingDB.GetEmailRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 username 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPhonenumber", ReplyAction="*")]
        ParkingPalsClientSide.parkingDB.GetPhonenumberResponse GetPhonenumber(ParkingPalsClientSide.parkingDB.GetPhonenumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPhonenumber", ReplyAction="*")]
        System.Threading.Tasks.Task<ParkingPalsClientSide.parkingDB.GetPhonenumberResponse> GetPhonenumberAsync(ParkingPalsClientSide.parkingDB.GetPhonenumberRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 username 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAccountType", ReplyAction="*")]
        ParkingPalsClientSide.parkingDB.GetAccountTypeResponse GetAccountType(ParkingPalsClientSide.parkingDB.GetAccountTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAccountType", ReplyAction="*")]
        System.Threading.Tasks.Task<ParkingPalsClientSide.parkingDB.GetAccountTypeResponse> GetAccountTypeAsync(ParkingPalsClientSide.parkingDB.GetAccountTypeRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 ticketid 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/checkTicket", ReplyAction="*")]
        ParkingPalsClientSide.parkingDB.checkTicketResponse checkTicket(ParkingPalsClientSide.parkingDB.checkTicketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/checkTicket", ReplyAction="*")]
        System.Threading.Tasks.Task<ParkingPalsClientSide.parkingDB.checkTicketResponse> checkTicketAsync(ParkingPalsClientSide.parkingDB.checkTicketRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userid 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/checkUser", ReplyAction="*")]
        ParkingPalsClientSide.parkingDB.checkUserResponse checkUser(ParkingPalsClientSide.parkingDB.checkUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/checkUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ParkingPalsClientSide.parkingDB.checkUserResponse> checkUserAsync(ParkingPalsClientSide.parkingDB.checkUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ParkingPalsClientSide.parkingDB.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ParkingPalsClientSide.parkingDB.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ParkingPalsClientSide.parkingDB.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ParkingPalsClientSide.parkingDB.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostUser", Namespace="http://tempuri.org/", Order=0)]
        public ParkingPalsClientSide.parkingDB.PostUserRequestBody Body;
        
        public PostUserRequest() {
        }
        
        public PostUserRequest(ParkingPalsClientSide.parkingDB.PostUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PostUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string firstname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lastname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string phonenumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string accounttype;
        
        public PostUserRequestBody() {
        }
        
        public PostUserRequestBody(string username, string firstname, string lastname, string email, string phonenumber, string password, string accounttype) {
            this.username = username;
            this.firstname = firstname;
            this.lastname = lastname;
            this.email = email;
            this.phonenumber = phonenumber;
            this.password = password;
            this.accounttype = accounttype;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public ParkingPalsClientSide.parkingDB.PostUserResponseBody Body;
        
        public PostUserResponse() {
        }
        
        public PostUserResponse(ParkingPalsClientSide.parkingDB.PostUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PostUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool PostUserResult;
        
        public PostUserResponseBody() {
        }
        
        public PostUserResponseBody(bool PostUserResult) {
            this.PostUserResult = PostUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutUser", Namespace="http://tempuri.org/", Order=0)]
        public ParkingPalsClientSide.parkingDB.PutUserRequestBody Body;
        
        public PutUserRequest() {
        }
        
        public PutUserRequest(ParkingPalsClientSide.parkingDB.PutUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PutUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string phonenumber;
        
        public PutUserRequestBody() {
        }
        
        public PutUserRequestBody(string username, string email, string password, string phonenumber) {
            this.username = username;
            this.email = email;
            this.password = password;
            this.phonenumber = phonenumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public ParkingPalsClientSide.parkingDB.PutUserResponseBody Body;
        
        public PutUserResponse() {
        }
        
        public PutUserResponse(ParkingPalsClientSide.parkingDB.PutUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PutUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool PutUserResult;
        
        public PutUserResponseBody() {
        }
        
        public PutUserResponseBody(bool PutUserResult) {
            this.PutUserResult = PutUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsernameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsername", Namespace="http://tempuri.org/", Order=0)]
        public ParkingPalsClientSide.parkingDB.GetUsernameRequestBody Body;
        
        public GetUsernameRequest() {
        }
        
        public GetUsernameRequest(ParkingPalsClientSide.parkingDB.GetUsernameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUsernameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public GetUsernameRequestBody() {
        }
        
        public GetUsernameRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsernameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsernameResponse", Namespace="http://tempuri.org/", Order=0)]
        public ParkingPalsClientSide.parkingDB.GetUsernameResponseBody Body;
        
        public GetUsernameResponse() {
        }
        
        public GetUsernameResponse(ParkingPalsClientSide.parkingDB.GetUsernameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUsernameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUsernameResult;
        
        public GetUsernameResponseBody() {
        }
        
        public GetUsernameResponseBody(string GetUsernameResult) {
            this.GetUsernameResult = GetUsernameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmail", Namespace="http://tempuri.org/", Order=0)]
        public ParkingPalsClientSide.parkingDB.GetEmailRequestBody Body;
        
        public GetEmailRequest() {
        }
        
        public GetEmailRequest(ParkingPalsClientSide.parkingDB.GetEmailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public GetEmailRequestBody() {
        }
        
        public GetEmailRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmailResponse", Namespace="http://tempuri.org/", Order=0)]
        public ParkingPalsClientSide.parkingDB.GetEmailResponseBody Body;
        
        public GetEmailResponse() {
        }
        
        public GetEmailResponse(ParkingPalsClientSide.parkingDB.GetEmailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetEmailResult;
        
        public GetEmailResponseBody() {
        }
        
        public GetEmailResponseBody(string GetEmailResult) {
            this.GetEmailResult = GetEmailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPhonenumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPhonenumber", Namespace="http://tempuri.org/", Order=0)]
        public ParkingPalsClientSide.parkingDB.GetPhonenumberRequestBody Body;
        
        public GetPhonenumberRequest() {
        }
        
        public GetPhonenumberRequest(ParkingPalsClientSide.parkingDB.GetPhonenumberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPhonenumberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public GetPhonenumberRequestBody() {
        }
        
        public GetPhonenumberRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPhonenumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPhonenumberResponse", Namespace="http://tempuri.org/", Order=0)]
        public ParkingPalsClientSide.parkingDB.GetPhonenumberResponseBody Body;
        
        public GetPhonenumberResponse() {
        }
        
        public GetPhonenumberResponse(ParkingPalsClientSide.parkingDB.GetPhonenumberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPhonenumberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPhonenumberResult;
        
        public GetPhonenumberResponseBody() {
        }
        
        public GetPhonenumberResponseBody(string GetPhonenumberResult) {
            this.GetPhonenumberResult = GetPhonenumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccountTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccountType", Namespace="http://tempuri.org/", Order=0)]
        public ParkingPalsClientSide.parkingDB.GetAccountTypeRequestBody Body;
        
        public GetAccountTypeRequest() {
        }
        
        public GetAccountTypeRequest(ParkingPalsClientSide.parkingDB.GetAccountTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAccountTypeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public GetAccountTypeRequestBody() {
        }
        
        public GetAccountTypeRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccountTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccountTypeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ParkingPalsClientSide.parkingDB.GetAccountTypeResponseBody Body;
        
        public GetAccountTypeResponse() {
        }
        
        public GetAccountTypeResponse(ParkingPalsClientSide.parkingDB.GetAccountTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAccountTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAccountTypeResult;
        
        public GetAccountTypeResponseBody() {
        }
        
        public GetAccountTypeResponseBody(string GetAccountTypeResult) {
            this.GetAccountTypeResult = GetAccountTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkTicketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkTicket", Namespace="http://tempuri.org/", Order=0)]
        public ParkingPalsClientSide.parkingDB.checkTicketRequestBody Body;
        
        public checkTicketRequest() {
        }
        
        public checkTicketRequest(ParkingPalsClientSide.parkingDB.checkTicketRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class checkTicketRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ticketid;
        
        public checkTicketRequestBody() {
        }
        
        public checkTicketRequestBody(string ticketid) {
            this.ticketid = ticketid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkTicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkTicketResponse", Namespace="http://tempuri.org/", Order=0)]
        public ParkingPalsClientSide.parkingDB.checkTicketResponseBody Body;
        
        public checkTicketResponse() {
        }
        
        public checkTicketResponse(ParkingPalsClientSide.parkingDB.checkTicketResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class checkTicketResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool checkTicketResult;
        
        public checkTicketResponseBody() {
        }
        
        public checkTicketResponseBody(bool checkTicketResult) {
            this.checkTicketResult = checkTicketResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkUser", Namespace="http://tempuri.org/", Order=0)]
        public ParkingPalsClientSide.parkingDB.checkUserRequestBody Body;
        
        public checkUserRequest() {
        }
        
        public checkUserRequest(ParkingPalsClientSide.parkingDB.checkUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class checkUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userid;
        
        public checkUserRequestBody() {
        }
        
        public checkUserRequestBody(string userid) {
            this.userid = userid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public ParkingPalsClientSide.parkingDB.checkUserResponseBody Body;
        
        public checkUserResponse() {
        }
        
        public checkUserResponse(ParkingPalsClientSide.parkingDB.checkUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class checkUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool checkUserResult;
        
        public checkUserResponseBody() {
        }
        
        public checkUserResponseBody(bool checkUserResult) {
            this.checkUserResult = checkUserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ParkingDBWSSoapChannel : ParkingPalsClientSide.parkingDB.ParkingDBWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ParkingDBWSSoapClient : System.ServiceModel.ClientBase<ParkingPalsClientSide.parkingDB.ParkingDBWSSoap>, ParkingPalsClientSide.parkingDB.ParkingDBWSSoap {
        
        public ParkingDBWSSoapClient() {
        }
        
        public ParkingDBWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ParkingDBWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParkingDBWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParkingDBWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ParkingPalsClientSide.parkingDB.HelloWorldResponse ParkingPalsClientSide.parkingDB.ParkingDBWSSoap.HelloWorld(ParkingPalsClientSide.parkingDB.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ParkingPalsClientSide.parkingDB.HelloWorldRequest inValue = new ParkingPalsClientSide.parkingDB.HelloWorldRequest();
            inValue.Body = new ParkingPalsClientSide.parkingDB.HelloWorldRequestBody();
            ParkingPalsClientSide.parkingDB.HelloWorldResponse retVal = ((ParkingPalsClientSide.parkingDB.ParkingDBWSSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ParkingPalsClientSide.parkingDB.HelloWorldResponse> ParkingPalsClientSide.parkingDB.ParkingDBWSSoap.HelloWorldAsync(ParkingPalsClientSide.parkingDB.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ParkingPalsClientSide.parkingDB.HelloWorldResponse> HelloWorldAsync() {
            ParkingPalsClientSide.parkingDB.HelloWorldRequest inValue = new ParkingPalsClientSide.parkingDB.HelloWorldRequest();
            inValue.Body = new ParkingPalsClientSide.parkingDB.HelloWorldRequestBody();
            return ((ParkingPalsClientSide.parkingDB.ParkingDBWSSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ParkingPalsClientSide.parkingDB.PostUserResponse ParkingPalsClientSide.parkingDB.ParkingDBWSSoap.PostUser(ParkingPalsClientSide.parkingDB.PostUserRequest request) {
            return base.Channel.PostUser(request);
        }
        
        public bool PostUser(string username, string firstname, string lastname, string email, string phonenumber, string password, string accounttype) {
            ParkingPalsClientSide.parkingDB.PostUserRequest inValue = new ParkingPalsClientSide.parkingDB.PostUserRequest();
            inValue.Body = new ParkingPalsClientSide.parkingDB.PostUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.firstname = firstname;
            inValue.Body.lastname = lastname;
            inValue.Body.email = email;
            inValue.Body.phonenumber = phonenumber;
            inValue.Body.password = password;
            inValue.Body.accounttype = accounttype;
            ParkingPalsClientSide.parkingDB.PostUserResponse retVal = ((ParkingPalsClientSide.parkingDB.ParkingDBWSSoap)(this)).PostUser(inValue);
            return retVal.Body.PostUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ParkingPalsClientSide.parkingDB.PostUserResponse> ParkingPalsClientSide.parkingDB.ParkingDBWSSoap.PostUserAsync(ParkingPalsClientSide.parkingDB.PostUserRequest request) {
            return base.Channel.PostUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ParkingPalsClientSide.parkingDB.PostUserResponse> PostUserAsync(string username, string firstname, string lastname, string email, string phonenumber, string password, string accounttype) {
            ParkingPalsClientSide.parkingDB.PostUserRequest inValue = new ParkingPalsClientSide.parkingDB.PostUserRequest();
            inValue.Body = new ParkingPalsClientSide.parkingDB.PostUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.firstname = firstname;
            inValue.Body.lastname = lastname;
            inValue.Body.email = email;
            inValue.Body.phonenumber = phonenumber;
            inValue.Body.password = password;
            inValue.Body.accounttype = accounttype;
            return ((ParkingPalsClientSide.parkingDB.ParkingDBWSSoap)(this)).PostUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ParkingPalsClientSide.parkingDB.PutUserResponse ParkingPalsClientSide.parkingDB.ParkingDBWSSoap.PutUser(ParkingPalsClientSide.parkingDB.PutUserRequest request) {
            return base.Channel.PutUser(request);
        }
        
        public bool PutUser(string username, string email, string password, string phonenumber) {
            ParkingPalsClientSide.parkingDB.PutUserRequest inValue = new ParkingPalsClientSide.parkingDB.PutUserRequest();
            inValue.Body = new ParkingPalsClientSide.parkingDB.PutUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.email = email;
            inValue.Body.password = password;
            inValue.Body.phonenumber = phonenumber;
            ParkingPalsClientSide.parkingDB.PutUserResponse retVal = ((ParkingPalsClientSide.parkingDB.ParkingDBWSSoap)(this)).PutUser(inValue);
            return retVal.Body.PutUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ParkingPalsClientSide.parkingDB.PutUserResponse> ParkingPalsClientSide.parkingDB.ParkingDBWSSoap.PutUserAsync(ParkingPalsClientSide.parkingDB.PutUserRequest request) {
            return base.Channel.PutUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ParkingPalsClientSide.parkingDB.PutUserResponse> PutUserAsync(string username, string email, string password, string phonenumber) {
            ParkingPalsClientSide.parkingDB.PutUserRequest inValue = new ParkingPalsClientSide.parkingDB.PutUserRequest();
            inValue.Body = new ParkingPalsClientSide.parkingDB.PutUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.email = email;
            inValue.Body.password = password;
            inValue.Body.phonenumber = phonenumber;
            return ((ParkingPalsClientSide.parkingDB.ParkingDBWSSoap)(this)).PutUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ParkingPalsClientSide.parkingDB.GetUsernameResponse ParkingPalsClientSide.parkingDB.ParkingDBWSSoap.GetUsername(ParkingPalsClientSide.parkingDB.GetUsernameRequest request) {
            return base.Channel.GetUsername(request);
        }
        
        public string GetUsername(string username) {
            ParkingPalsClientSide.parkingDB.GetUsernameRequest inValue = new ParkingPalsClientSide.parkingDB.GetUsernameRequest();
            inValue.Body = new ParkingPalsClientSide.parkingDB.GetUsernameRequestBody();
            inValue.Body.username = username;
            ParkingPalsClientSide.parkingDB.GetUsernameResponse retVal = ((ParkingPalsClientSide.parkingDB.ParkingDBWSSoap)(this)).GetUsername(inValue);
            return retVal.Body.GetUsernameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ParkingPalsClientSide.parkingDB.GetUsernameResponse> ParkingPalsClientSide.parkingDB.ParkingDBWSSoap.GetUsernameAsync(ParkingPalsClientSide.parkingDB.GetUsernameRequest request) {
            return base.Channel.GetUsernameAsync(request);
        }
        
        public System.Threading.Tasks.Task<ParkingPalsClientSide.parkingDB.GetUsernameResponse> GetUsernameAsync(string username) {
            ParkingPalsClientSide.parkingDB.GetUsernameRequest inValue = new ParkingPalsClientSide.parkingDB.GetUsernameRequest();
            inValue.Body = new ParkingPalsClientSide.parkingDB.GetUsernameRequestBody();
            inValue.Body.username = username;
            return ((ParkingPalsClientSide.parkingDB.ParkingDBWSSoap)(this)).GetUsernameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ParkingPalsClientSide.parkingDB.GetEmailResponse ParkingPalsClientSide.parkingDB.ParkingDBWSSoap.GetEmail(ParkingPalsClientSide.parkingDB.GetEmailRequest request) {
            return base.Channel.GetEmail(request);
        }
        
        public string GetEmail(string username) {
            ParkingPalsClientSide.parkingDB.GetEmailRequest inValue = new ParkingPalsClientSide.parkingDB.GetEmailRequest();
            inValue.Body = new ParkingPalsClientSide.parkingDB.GetEmailRequestBody();
            inValue.Body.username = username;
            ParkingPalsClientSide.parkingDB.GetEmailResponse retVal = ((ParkingPalsClientSide.parkingDB.ParkingDBWSSoap)(this)).GetEmail(inValue);
            return retVal.Body.GetEmailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ParkingPalsClientSide.parkingDB.GetEmailResponse> ParkingPalsClientSide.parkingDB.ParkingDBWSSoap.GetEmailAsync(ParkingPalsClientSide.parkingDB.GetEmailRequest request) {
            return base.Channel.GetEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<ParkingPalsClientSide.parkingDB.GetEmailResponse> GetEmailAsync(string username) {
            ParkingPalsClientSide.parkingDB.GetEmailRequest inValue = new ParkingPalsClientSide.parkingDB.GetEmailRequest();
            inValue.Body = new ParkingPalsClientSide.parkingDB.GetEmailRequestBody();
            inValue.Body.username = username;
            return ((ParkingPalsClientSide.parkingDB.ParkingDBWSSoap)(this)).GetEmailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ParkingPalsClientSide.parkingDB.GetPhonenumberResponse ParkingPalsClientSide.parkingDB.ParkingDBWSSoap.GetPhonenumber(ParkingPalsClientSide.parkingDB.GetPhonenumberRequest request) {
            return base.Channel.GetPhonenumber(request);
        }
        
        public string GetPhonenumber(string username) {
            ParkingPalsClientSide.parkingDB.GetPhonenumberRequest inValue = new ParkingPalsClientSide.parkingDB.GetPhonenumberRequest();
            inValue.Body = new ParkingPalsClientSide.parkingDB.GetPhonenumberRequestBody();
            inValue.Body.username = username;
            ParkingPalsClientSide.parkingDB.GetPhonenumberResponse retVal = ((ParkingPalsClientSide.parkingDB.ParkingDBWSSoap)(this)).GetPhonenumber(inValue);
            return retVal.Body.GetPhonenumberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ParkingPalsClientSide.parkingDB.GetPhonenumberResponse> ParkingPalsClientSide.parkingDB.ParkingDBWSSoap.GetPhonenumberAsync(ParkingPalsClientSide.parkingDB.GetPhonenumberRequest request) {
            return base.Channel.GetPhonenumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<ParkingPalsClientSide.parkingDB.GetPhonenumberResponse> GetPhonenumberAsync(string username) {
            ParkingPalsClientSide.parkingDB.GetPhonenumberRequest inValue = new ParkingPalsClientSide.parkingDB.GetPhonenumberRequest();
            inValue.Body = new ParkingPalsClientSide.parkingDB.GetPhonenumberRequestBody();
            inValue.Body.username = username;
            return ((ParkingPalsClientSide.parkingDB.ParkingDBWSSoap)(this)).GetPhonenumberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ParkingPalsClientSide.parkingDB.GetAccountTypeResponse ParkingPalsClientSide.parkingDB.ParkingDBWSSoap.GetAccountType(ParkingPalsClientSide.parkingDB.GetAccountTypeRequest request) {
            return base.Channel.GetAccountType(request);
        }
        
        public string GetAccountType(string username) {
            ParkingPalsClientSide.parkingDB.GetAccountTypeRequest inValue = new ParkingPalsClientSide.parkingDB.GetAccountTypeRequest();
            inValue.Body = new ParkingPalsClientSide.parkingDB.GetAccountTypeRequestBody();
            inValue.Body.username = username;
            ParkingPalsClientSide.parkingDB.GetAccountTypeResponse retVal = ((ParkingPalsClientSide.parkingDB.ParkingDBWSSoap)(this)).GetAccountType(inValue);
            return retVal.Body.GetAccountTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ParkingPalsClientSide.parkingDB.GetAccountTypeResponse> ParkingPalsClientSide.parkingDB.ParkingDBWSSoap.GetAccountTypeAsync(ParkingPalsClientSide.parkingDB.GetAccountTypeRequest request) {
            return base.Channel.GetAccountTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ParkingPalsClientSide.parkingDB.GetAccountTypeResponse> GetAccountTypeAsync(string username) {
            ParkingPalsClientSide.parkingDB.GetAccountTypeRequest inValue = new ParkingPalsClientSide.parkingDB.GetAccountTypeRequest();
            inValue.Body = new ParkingPalsClientSide.parkingDB.GetAccountTypeRequestBody();
            inValue.Body.username = username;
            return ((ParkingPalsClientSide.parkingDB.ParkingDBWSSoap)(this)).GetAccountTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ParkingPalsClientSide.parkingDB.checkTicketResponse ParkingPalsClientSide.parkingDB.ParkingDBWSSoap.checkTicket(ParkingPalsClientSide.parkingDB.checkTicketRequest request) {
            return base.Channel.checkTicket(request);
        }
        
        public bool checkTicket(string ticketid) {
            ParkingPalsClientSide.parkingDB.checkTicketRequest inValue = new ParkingPalsClientSide.parkingDB.checkTicketRequest();
            inValue.Body = new ParkingPalsClientSide.parkingDB.checkTicketRequestBody();
            inValue.Body.ticketid = ticketid;
            ParkingPalsClientSide.parkingDB.checkTicketResponse retVal = ((ParkingPalsClientSide.parkingDB.ParkingDBWSSoap)(this)).checkTicket(inValue);
            return retVal.Body.checkTicketResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ParkingPalsClientSide.parkingDB.checkTicketResponse> ParkingPalsClientSide.parkingDB.ParkingDBWSSoap.checkTicketAsync(ParkingPalsClientSide.parkingDB.checkTicketRequest request) {
            return base.Channel.checkTicketAsync(request);
        }
        
        public System.Threading.Tasks.Task<ParkingPalsClientSide.parkingDB.checkTicketResponse> checkTicketAsync(string ticketid) {
            ParkingPalsClientSide.parkingDB.checkTicketRequest inValue = new ParkingPalsClientSide.parkingDB.checkTicketRequest();
            inValue.Body = new ParkingPalsClientSide.parkingDB.checkTicketRequestBody();
            inValue.Body.ticketid = ticketid;
            return ((ParkingPalsClientSide.parkingDB.ParkingDBWSSoap)(this)).checkTicketAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ParkingPalsClientSide.parkingDB.checkUserResponse ParkingPalsClientSide.parkingDB.ParkingDBWSSoap.checkUser(ParkingPalsClientSide.parkingDB.checkUserRequest request) {
            return base.Channel.checkUser(request);
        }
        
        public bool checkUser(string userid) {
            ParkingPalsClientSide.parkingDB.checkUserRequest inValue = new ParkingPalsClientSide.parkingDB.checkUserRequest();
            inValue.Body = new ParkingPalsClientSide.parkingDB.checkUserRequestBody();
            inValue.Body.userid = userid;
            ParkingPalsClientSide.parkingDB.checkUserResponse retVal = ((ParkingPalsClientSide.parkingDB.ParkingDBWSSoap)(this)).checkUser(inValue);
            return retVal.Body.checkUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ParkingPalsClientSide.parkingDB.checkUserResponse> ParkingPalsClientSide.parkingDB.ParkingDBWSSoap.checkUserAsync(ParkingPalsClientSide.parkingDB.checkUserRequest request) {
            return base.Channel.checkUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ParkingPalsClientSide.parkingDB.checkUserResponse> checkUserAsync(string userid) {
            ParkingPalsClientSide.parkingDB.checkUserRequest inValue = new ParkingPalsClientSide.parkingDB.checkUserRequest();
            inValue.Body = new ParkingPalsClientSide.parkingDB.checkUserRequestBody();
            inValue.Body.userid = userid;
            return ((ParkingPalsClientSide.parkingDB.ParkingDBWSSoap)(this)).checkUserAsync(inValue);
        }
    }
}
